<?php 
/*
 *
 * Template Name: Content Sidebar Sidebar
 * Single Post Template: Content Sidebar Sidebar
 * This is the content-sidebar-sidebar.php file for the inLine WordPress theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you need to edit the core theme, please make a child theme instead.
 *
 */

add_action( 'inline_after_content', 'inline_alternate_sidebar' );
add_action( 'the_post', 'inline_post_content_helper' );

inline();