<?php 
/**
 *
 * This is the footer.php file for the inLine theme.
 * 
 * DO NOT EDIT THIS FILE! This is part of the inLine core theme and is overwritten in updates.
 * If you want to make changes, please create and modify a child theme that references the inLine parent theme.
 *
 * @package inLine
 * @since 1.0
 * 
 */

do_action( 'inline_before_footer' );
do_action( 'inline_footer' );
do_action( 'inline_after_footer' );
do_action( 'inline_after_wireframe' );
?>

</html>