<?php
/**
 *
 * This is the header.php file for the inLine theme.
 * 
 * DO NOT EDIT THIS FILE! This is part of the inLine core theme and is overwritten in updates.
 * If you want to make changes, please create and modify a child theme that references the inLine parent theme.
 *
 * @package inLine
 * @since 1.0
 * 
 */

do_action( 'inline_head_doctype' );
do_action( 'inline_title' );
do_action( 'inline_style' );
do_action( 'inline_favicon' );
wp_head();

?>
</head>
<?php

do_action( 'inline_before_wireframe' );
do_action( 'inline_before_header' );
do_action( 'inline_header' );
do_action( 'inline_after_header' );