<?php 
/*
 *
 * Template Name: Left Sidebar
 * Single Post Template: Left Sidebar
 * This is the left-sidebar-template.php file for the inLine WordPress theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you need to edit the core theme, please make a child theme instead.
 *
 */

add_action( 'the_post', 'inline_post_content_helper' );

inline();
