<?php 
/*
 *
 * Template Name: Archives
 * This is the page-archives.php file for the inLine WordPress theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you need to edit the core theme, please make a child theme instead.
 *
 */

add_action( 'inline_after_post_content', 'inline_archive_structure_start', 5 );
add_action( 'inline_after_post_content', 'inline_archive_left_column_start' );
add_action( 'inline_after_post_content', 'inline_archive_left_column' );
add_action( 'inline_after_post_content', 'inline_archive_left_column_end' );
add_action( 'inline_after_post_content', 'inline_archive_right_column_start' );
add_action( 'inline_after_post_content', 'inline_archive_right_column' );
add_action( 'inline_after_post_content', 'inline_archive_right_column_end' );
add_action( 'inline_after_post_content', 'inline_archive_search_form' );
add_action( 'inline_after_post_content', 'inline_archive_structure_end', 15 );

inline_page_archives_layout();

inline();