<?php 
/*
 *
 * This is the search.php file for the inLine WordPress theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you need to edit the core theme, please make a child theme instead.
 *
 */

add_action( 'inline_alternate_loop', 'inline_search_no_results' );

inline();