<?php 
/*
 *
 * This is the sidebar.php file for the inLine WordPress theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you need to edit the core theme, please make a child theme instead.
 *
 */
 
do_action( 'inline_sidebar' );

