<?php
/**
 *
 * This is the init.php file for the inLine theme. It's the backbone of the inLine theme.
 *
 * ABSOLUTELY DO NOT EDIT THIS FILE! IF YOU DO, YOUR SITE *WILL* BREAK.
 *
 * The init.php file sets up our basic necessities like constants and our theme structure.
 *
 * @package inLine
 * @since 1.0
 * 
 */

add_action( 'inline_init', 'inline_constants' );
/**
 *
 * This function adds all the constants that can be used for the inLine theme.
 *
 * @since 1.0
 *
 */
function inline_constants() {

	// Define directory constants
	define( 'PARENT_DIR', get_template_directory() );
	define( 'CHILD_DIR', get_stylesheet_directory() );
	define( 'INLINE_IMAGES_DIR', PARENT_DIR . '/images' );
	define( 'INLINE_LIB_DIR', PARENT_DIR . '/lib' );
	define( 'INLINE_ADMIN_DIR', INLINE_LIB_DIR . '/admin' );
	define( 'INLINE_BUILD_DIR', INLINE_LIB_DIR . '/build' );
	define( 'INLINE_FUNCTIONS_DIR', INLINE_LIB_DIR . '/functions' );
	define( 'INLINE_JS_DIR', INLINE_LIB_DIR . '/js' );
	define( 'INLINE_LANGUAGES_DIR', INLINE_LIB_DIR . '/languages' );
	define( 'INLINE_RESOURCES_DIR', INLINE_LIB_DIR . '/resources' );

	// Define URL constants
	define( 'PARENT_URL', get_template_directory_uri() );
	define( 'CHILD_URL', get_stylesheet_directory_uri() );
	define( 'INLINE_IMAGES_URL', PARENT_URL . '/images' );
	define( 'INLINE_LIB_URL', PARENT_URL . '/lib' );
	define( 'INLINE_ADMIN_URL', INLINE_LIB_URL . '/admin' );
	define( 'INLINE_BUILD_URL', INLINE_LIB_URL . '/build' );
	define( 'INLINE_FUNCTIONS_URL', INLINE_LIB_URL . '/functions' );
	define( 'INLINE_JS_URL', INLINE_LIB_URL . '/js' );
	define( 'INLINE_LANGUAGES_URL', INLINE_LIB_URL . '/languages' );
	define( 'INLINE_RESOURCES_URL', INLINE_LIB_URL . '/resources' );

}

add_action( 'inline_init', 'inline_mobilize_theme' );
/**
 *
 * This function kick-starts our theme by initializing all of our structure files.
 *
 * The following actions are added to this hook:
 *
 * inline_pre_theme 
 *
 * @since 1.0
 *
 */
function inline_mobilize_theme() {

do_action( 'inline_pre_theme' );

	// Load the theme
	load_template( INLINE_LIB_DIR . '/theme.php' );
	
	// Load functions
	load_template( INLINE_FUNCTIONS_DIR . '/hooks.php' );
	load_template( INLINE_FUNCTIONS_DIR . '/search.php' );
	load_template( INLINE_FUNCTIONS_DIR . '/register-nav.php' );
	load_template( INLINE_FUNCTIONS_DIR . '/register-sidebar.php' );
	load_template( INLINE_FUNCTIONS_DIR . '/page-nav.php' );
	load_template( INLINE_FUNCTIONS_DIR . '/main-body-classes.php' );
	load_template( INLINE_FUNCTIONS_DIR . '/i18n.php' );

	// Load admin structure
	load_template( INLINE_ADMIN_DIR . '/admin-settings.php' );
	load_template( INLINE_ADMIN_DIR . '/update-template.php' );
	load_template( INLINE_ADMIN_DIR . '/body-classes.php' );
	
	// Load javascript
	load_template( INLINE_JS_DIR . '/mobilize-js.php' );
	
	// Load build
	load_template( INLINE_BUILD_DIR . '/header.php' );
	load_template( INLINE_BUILD_DIR . '/top-section.php' );
	load_template( INLINE_BUILD_DIR . '/post.php' );
	load_template( INLINE_BUILD_DIR . '/content.php' );
	load_template( INLINE_BUILD_DIR . '/sidebar.php' );
	load_template( INLINE_BUILD_DIR . '/footer.php' );
	load_template( INLINE_BUILD_DIR . '/comments.php' );
	
	// Load our resources
	load_template( INLINE_RESOURCES_DIR . '/post-template-setup.php' );
	load_template( INLINE_RESOURCES_DIR . '/page-archives-template.php' );

}

add_action( 'inline_init', 'inline_theme_support' );
/**
 *
 * This function adds all the theme support needed to make sure that common WordPress items are included. This function also adds our image sizes.
 *
 * @since 1.0
 *
 */
function inline_theme_support() {

	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'menus' );
	add_theme_support( 'post-thumbnails' );
	
	global $wp_version;
	if ( version_compare( $wp_version, '3.4', '>=' ) ) 
		add_theme_support( 'custom-background' ); 
	else
		add_custom_background();
		
	add_editor_style();
	add_image_size( 'post-thumb', 120, 120, TRUE );
	add_image_size( 'post-full', 590, 120, TRUE );
	add_image_size( 'post-full-template-mid', 490, 120, TRUE );
	add_image_size( 'post-full-template-side', 470, 120, TRUE );
	add_image_size( 'post-full-width', 910, 120, TRUE );

}

add_action( 'inline_init', 'inline_default_content_width', 9 );
/**
 *
 * This outputs our content width default size for video embeds.
 *
 * @since 1.0
 *
 */
function inline_default_content_width() {

	if ( ! isset( $content_width ) )
		$content_width = 600;
		
}

// Fire the inline_init hook
do_action( 'inline_init' );