<?php
/**
 *
 * This is the theme.php file for the inLine theme.
 *
 * ABSOLUTELY DO NOT EDIT THIS FILE! IF YOU DO, YOUR SITE *WILL* BREAK.
 *
 * The theme.php file gives us our core layout and pulls in all the necessary items to manipulate template files.
 *
 * @package inLine
 * @since 1.0
 * 
 */
 
function inline() {

	get_header();

	do_action( 'inline_top_section' );
	do_action( 'inline_before_main_content' ); // Adds a hook before the #main-content div
	do_action( 'inline_content' );
	do_action( 'inline_after_main_content' );

	get_footer();

}